import Head from 'next/head'
import type {AppProps} from 'next/app'
import '../styles/globals.scss'

function MyApp({Component, pageProps}: AppProps) {
  return <>
    <Head>
      <title>Hello NextJS</title>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" href="/favicon.ico"/>
    </Head>
    <Component {...pageProps} /></>
}

export default MyApp
